version: '3.10-alpine'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  web:
    build: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8070
    ports:
      - "8070:8070"
    environment:
      - SECRET_KEY=django-insecure-jh_x#q8%**1l4qtxj^=h(r9(89m&968rlk$exn5jn=t+@g+o!0
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=127.0.0.1 localhost 0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_NAME=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - redis
      - db